# Generated by Django 4.1.3 on 2022-11-19 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_announced', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('subvenue', models.CharField(default='', max_length=128)),
                ('address', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Event', 'Event')], default=('Article', 'Article'), max_length=32)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Private', 'Private'), ('Public', 'Public'), ('Password', 'Password')], default=('Draft', 'Draft'), max_length=32)),
                ('title', models.CharField(default='', max_length=256)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(default='')),
                ('brand', models.ManyToManyField(to='backend.brand')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.city')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.collection')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.season')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.venue')),
            ],
        ),
    ]
