# Generated by Django 4.1.3 on 2022-11-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
    ]
