# Generated by Django 4.1.3 on 2022-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public'), (3, 'Password')], default=(0, 'Draft'), max_length=32),
        ),
    ]
