# Generated by Django 4.1.3 on 2022-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='to_be_announced',
        ),
        migrations.AddField(
            model_name='post',
            name='to_be_announced',
            field=models.BooleanField(default=True),
        ),
    ]
