# Generated by Django 4.1.3 on 2022-11-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_post_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.gallery'),
        ),
    ]
