# Generated by Django 4.1.3 on 2022-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Private', 'Private'), ('Public', 'Public'), ('Password', 'Password')], default=('Draft', 'Draft'), max_length=32),
        ),
    ]
