# Generated by Django 4.1.3 on 2022-11-28 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_venue_to_be_announced_post_to_be_announced'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
