# Generated by Django 4.1.3 on 2022-11-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_country_city_latitude_city_longitude_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.city'),
        ),
    ]
