# Generated by Django 4.1.3 on 2022-11-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_venue_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
    ]
